config/routes.rb
Rails.application.routes.draw do
  get 'sessions/logout_page'
  get 'session/logout_page'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  get '/logout', to: 'sessions#logout_page'

  resources :users, only: [:new, :show] do
    collection do
      get :my_favorites
      get :my_items
      get :my_purchased_items
    end
  end
  
  resources :cards, only: [:new, :create, :show] do
    collection do
      delete :delete
    end
    member do
      post :purchase
      get :new_for_purchase
      post :create_for_purchase
    end
  end

  resources :profiles, only: [:new, :create] do
    collection do
      get 'step1'
      get 'step2'
    end
  end

  resources :shipping_datas, only: [:new, :create] do
    collection do
      get 'step1'
      get 'step2'
    end
  end


  resources :items, except: [:index] do
    collection do
      get :destroy_existing_image
    end
    
    member do
      get :purchase_confirmation
    end 

    collection do
      get :search_by_ransack
      get 'search'
      post :create_favorite
      post :destroy_favorite
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :comments,  only: :create
  end

  root 'items#index'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2], password_length: 7..128
  validates :name, presence: true, uniqueness: true

  def self.form_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
  has_one :profile, dependent: :destroy
  has_one :buyer_shipping_data, dependent: :destroy
  has_many :cards
  has_many :sns_credentials
  has_many :comments
  has_many :favorites
  has_many :items, dependent: :destroy
  has_many :favorite_items, through: :favorites, source: :item
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.form_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  #GET /resource/sign_up
  #def new
    #super
    #render layout: 'sub_application'
  #end

  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    render layout: 'sub_application'
  #   super
  end

  def callback
    auth = request.env["omniauth.auth"]
    user = User.find_by(provider: auth["provider"], uid: auth["uid"]) || User.create_with_facebook(auth)
    session[:user_id] = user.id
    redirect_back_or root_path
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def my_favorites
    @items = current_user.favorite_items
  end

  def my_items
    @items = current_user.items
  end

  def my_purchased_items
    @items = Item.where(buyer_id: current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side-bar.html.haml
.container_contents_side
  .container_contents_side_title
    設定
  %ul.container_contents_side_contents
    %li
      = link_to "プロフィール", user_path(current_user.id)
      .container_contents_side_contents_profile_right
    %li
      = link_to "本人確認情報", new_profile_path
      .container_contents_side_contents_address_right
    %li
      = link_to "送付先情報", new_shipping_data_path
    %li
      = link_to "お気に入り一覧", my_favorites_users_path
    %li
      = link_to "出品した商品",  my_items_users_path
    %li
      = link_to "購入した商品", my_purchased_items_users_path
    %li
      = link_to "支払い方法", new_card_path
    %li
      = link_to "メール / パスワード","#"
      .container_contents_side_contents_mailpass_right
    %li
      = link_to "ログアウト", logout_path, class: "container_contents_side_contents_logout"
      .container_contents_side_contents_logout_right

app/views/users/address_page.html.haml
.container
  .container_contents
    .container_contents_main
      .container_contents_main_address
        .container_contents_main_address_inside
          = link_to "商品送付先住所情報", "#", class: "container_contents_main_address_inside_bottun"
      
    .container_contents_side
      .container_contents_side_title
        設定
      %ul.container_contents_side_contents
        %li.container_contents_side_contents_profile
          = link_to "プロフィール","#"
          .container_contents_side_contents_profile_right
        %li.container_contents_side_contents_address
          = link_to "住所変更", address_page_path
          .container_contents_side_contents_address_right
        %li.container_contents_side_contents_card
          = link_to "支払い方法", "/card_page"
          .container_contents_side_contents_card_right
        %li.container_contents_side_contents_mailpass
          = link_to "メール / パスワード","#"
          .container_contents_side_contents_mailpass_right
        %li.container_contents_side_contents_logout
          = link_to "ログアウト", "/logout"
          .container_contents_side_contents_logout_right

app/views/users/my_favorites.html.haml
- breadcrumb :my_favorites
= render partial: "layouts/breadcrumbs"
.container
  .container_contents
    #items.container_contents_main
      .container_contents_main__top
        お気に入り一覧
      %ul
        - @items.each do |item|
          %li
            = link_to item_path(item.id) do
              = image_tag item.images.first.image.url, height: '48', width: '48'
              .container_contents_main__item__information
                %div
                  = item.name
                %div
                  = "¥#{item.price}"


    = render partial: "users/side-bar"

app/views/users/my_items.html.haml
- breadcrumb :my_items
= render partial: "layouts/breadcrumbs"
.container
  .container_contents
    #items.container_contents_main
      .container_contents_main__top
        出品した商品
      %ul
        - @items.each do |item|
          %li
            = link_to item_path(item.id) do
              = image_tag item.images.first.image.url, height: '48', width: '48'
              .container_contents_main__item__information
                %div
                  = item.name
                .fav-and-com
                  %span.fav
                    %i.fa.fa-star
                    = item.users.length
                  %span.com
                    %i.fa.fa-comment
                    = item.comments.length

                  
                  


    = render partial: "users/side-bar"

app/views/users/my_purchased_items.html.haml
- breadcrumb :my_purchased_items
= render partial: "layouts/breadcrumbs"
.container
  .container_contents
    #items.container_contents_main
      .container_contents_main__top
        購入した商品
      %ul
        - @items.each do |item|
          %li
            = link_to item_path(item.id) do
              = image_tag item.images.first.image.url, height: '48', width: '48'
              .container_contents_main__item__information
                %div
                  = item.name
                .fav-and-com
                  %span.fav
                    %i.fa.fa-star
                    = item.users.length
                  %span.com
                    %i.fa.fa-comment
                    = item.comments.length

                  
                  


    = render partial: "users/side-bar"

app/views/users/show.html.haml
- breadcrumb :my_page
= render partial: "layouts/breadcrumbs"
.container
  .container_contents
    .container_contents_main
      .container_contents_main_icon
        .container_contents_main_icon_inside
          = link_to image_tag("member_photo_noimage_thumb.png", class: "container_contents_main_icon_inside_noimage"), "#"
          .container_contents_main_icon_inside_name
            = current_user.name
      .container_contents_main_profile
        .container_contents_main_profile_title
          プロフィール
          %hr
        .container_contents_main_profile_inside
      .container_contents_main_history
        .container_contents_main_history_title
          購入履歴
          %hr
        .container_contents_main_history_inside
    = render partial: "users/side-bar"