config/routes.rb
Rails.application.routes.draw do
  get 'sessions/logout_page'
  get 'session/logout_page'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  get '/logout', to: 'sessions#logout_page'

  resources :users, only: [:new, :show] do
    collection do
      get :my_favorites
      get :my_items
      get :my_purchased_items
    end
  end
  
  resources :cards, only: [:new, :create, :show] do
    collection do
      delete :delete
    end
    member do
      post :purchase
      get :new_for_purchase
      post :create_for_purchase
    end
  end

  resources :profiles, only: [:new, :create] do
    collection do
      get 'step1'
      get 'step2'
    end
  end

  resources :shipping_datas, only: [:new, :create] do
    collection do
      get 'step1'
      get 'step2'
    end
  end


  resources :items, except: [:index] do
    collection do
      get :destroy_existing_image
    end
    
    member do
      get :purchase_confirmation
    end 

    collection do
      get :search_by_ransack
      get 'search'
      post :create_favorite
      post :destroy_favorite
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :comments,  only: :create
  end

  root 'items#index'


end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :brand
  belongs_to :shipping
  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy 
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  accepts_nested_attributes_for :category
  accepts_nested_attributes_for :shipping
  accepts_nested_attributes_for :brand
  accepts_nested_attributes_for :images


  validates :name,length:{maximum:20}
  validates :description, length:{maximum:1000}
  validates :price,numericality:{greater_than_or_equal_to: 300} 

  with_options presence: true do
    validates :name
    validates :description
    validates :status
    validates :price
    validates :fee
    validates :profit
    validates :user_id
    validates :category_id 
    # validates :shipping_id
    validates :images

  end


  enum status: {
    新品未使用:1,未使用に近い:2,目立った傷や汚れなし:3,やや傷や汚れあり:4,傷や汚れあり:5,全体的に状態が悪い:6
  }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only:[:edit, :update]

  def index
  end

  def new
    @item = Item.new
    @item.build_shipping
    @item.build_brand
    @item.images.build
    @item.build_category
    render layout: 'sub_application'

    @category_parent_array = ["---"]
    @category_parent_array = Category.where(ancestry: nil)
  end

  def get_category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def show
    @item = Item.find(params[:id])
    @category = @item.category
    @children = @category.parent
    @parent = @children.parent
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def destroy
    if current_user.id != Item.find(params[:id]).user_id
      redirect_to item_path(params[:id])
    elsif Item.find(params[:id]).buyer_id.present?
      redirect_to item_path(params[:id])
    else
      item = Item.find(params[:id])
      
      if item.destroy
        redirect_to user_path(current_user.id)
      else
        flash.now[:alert] = '商品の削除に失敗しました。お手数ですが、もう一度やり直してください。'
        render :show
        return
      end
    end
  end

  def create
    fee = item_params[:price].to_i * 0.1
    profit = item_params[:price].to_i - fee
    @item = Item.new(item_params.merge(fee: fee, profit: profit))
    if @item.save!
      redirect_to root_path
      flash[:notice] = '出品ありがとうございます。下部の商品一覧よりご確認ください。'
    else
      redirect_to new_item_path
      flash[:alert] = '商品の出品に失敗しました。お手数ですが、もう一度やり直してください。'
    end
  end



  def search_by_ransack
  end


      
  def edit
    if current_user.id != Item.find(params[:id]).user_id
      redirect_to item_path(params[:id])
    elsif Item.find(params[:id]).buyer_id.present?
      redirect_to item_path(params[:id])
    else
      @categories = Category.where(ancestry: nil)
      @images = @item.images
      @shipping = @item.shipping
      @category = @item.category
      @children = @category.parent
      @parent = @children.parent
      gon.existing_images = Image.where(item_id: params[:id])
      render layout: 'sub_application'
    end
  end

  def destroy_existing_image
    image = Image.find(params[:id])
    if image.destroy
    else
      flash.now[:alert] = '画像の削除に失敗しました。お手数ですが、リロードしてもう一度やり直してください。'
    end
  end

  def update
    if current_user.id != Item.find(params[:id]).user_id
      redirect_to item_path(params[:id])
    elsif Item.find(params[:id]).buyer_id.present?
      redirect_to item_path(params[:id])
    else
      fee = item_params[:price].to_i * 0.1
      profit = item_params[:price].to_i - fee
      if @item.update(item_params.merge(fee: fee, profit: profit))
        redirect_to item_path(@item.id)
      else
        redirect_to edit_item_path(@item.id)
        flash[:alert] = '商品の変更に失敗しました。お手数ですが、もう一度やり直してください。'
      end
    end
  end

  def purchase_confirmation 
    if current_user.id == Item.find(params[:id]).user_id
      redirect_to item_path(params[:id])
    elsif Item.find(params[:id]).buyer_id.present?
      redirect_to item_path(params[:id])
    else
      @item = Item.find(params[:id])
      card = current_user.cards.first
      @shipping_data = current_user.buyer_shipping_data
      if card.blank?
        redirect_to new_for_purchase_card_path(@item.id)
        flash[:alert] = '購入にはクレジットカード登録が必要です'
        return
      elsif @shipping_data.blank?
        redirect_to new_shipping_data_path
        flash[:alert] = '購入には送付先情報の登録が必要です'
        return
      else
        Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
        customer = Payjp::Customer.retrieve(card.customer_id)
        @customer_card = customer.cards.retrieve(card.card_id)

        card_brand = @customer_card.brand      
        case card_brand
        when "Visa"
          @card_src = "visa.png"
        when "JCB"
          @card_src = "jcb.png"
        when "MasterCard"
          @card_src = "master-card.png"
        when "American Express"
          @card_src = "american_express.png"
        when "Diners Club"
          @card_src = "dinersclub.png"
        when "Discover"
          @card_src = "discover.png"
        end
      end
      render layout: 'sub_application'
    end
  end

  def create_favorite
    favorite = Favorite.new(item_id: params[:id], user_id: current_user.id)
    if favorite.save
    else
      redirect_to item_path(params[:id])
    end
  end

  def destroy_favorite
    favorite = Favorite.find_by(item_id: params[:id], user_id: current_user.id)
    if favorite.destroy
    else
      redirect_to item_path(params[:id])
    end
  end

  private
  def item_params
    params.require(:item).permit(:name,:description,:status,:price,:buyer_id,
    :category_id, brand_attributes: [:id ,:name],shipping_attributes:[:id,:burden, :shipping_way, :area, :day],
    images_attributes:[:id,:image])
    .merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
.exhibition
  = form_for @item,url: {action: 'update'} do |f|
    .exhibition__first
      .exhibition__first__syuppin
        出品画像
      .exhibition__first__must
        必須
      .exhibition__first__sheet
        最大5枚までアップロードできます
      .exhibition__first__box
        - index = 0
        - @images.each do |image|
          .item-image{"data-image" => "#{image.image.url}"}
            .item-image__content
              .item-image__content--icon
                %img{:height => "80", :src => "#{image.image.url}", :width => "114"}
                
                - index += 1
            .item-image__operetion
              .item-image__operetion--delete-existing-image 削除
        - if index > 5
          #exhibition__first__image{class: "item-num-5"}
            %label{class: "exhibition__first__image__picture"} 
              = f.fields_for :image do |i|
                = i.file_field :image, type: 'file', name: "item[images_attributes][][image]", value:"", id:"img-file",style: "display:none"
              #exhibition__first__image__picture
                = icon('fas fa-2x', 'camera')
            .exhibition__first__image__designation
              ドラッグアンドドロップ
            .exhibition__first__image__upload
              またはクリックしてファイルをアップロード
        - else
          #exhibition__first__image{class: "item-num-#{index}"}
            %label{class: "exhibition__first__image__picture"} 
              = f.fields_for :image, @images do |i|
                = i.file_field :image, type: 'file', name: "item[images_attributes][][image]", value:"", id:"img-file",style: "display:none"
              #exhibition__first__image__picture
                = icon('fas fa-2x', 'camera')
            .exhibition__first__image__designation
              ドラッグアンドドロップ
            .exhibition__first__image__upload
              またはクリックしてファイルをアップロード
      .exhibition__first__image__not-picture
        画像がありません
    .exhibition__second
      .exhibition__second__main
        .exhibition__second__main__name
          商品名
        .exhibition__second__main__must
          必須
        .exhibition__second__main__form
          = f.text_field :name, class: 'exhibition__second__main__form__comment', placeholder: 'type a message'
        .exhibition__second__main__alert2
          入力してください
        .exhibition__second__main__exhibition
          商品の説明
        .exhibition__second__main__must
          必須
        .exhibition__second__main__input
          = f.text_area :description, class: 'exhibition__second__main__input__form', placeholder: 'type a message'
        .exhibition__second__main__count
          0/1000
        .exhibition__second__main__alert
          入力してください
    .exhibition__third
      .exhibition__third__main
        .exhibition__third__main__details
          商品の詳細
        .exhibition__third__main__category
          カテゴリー
        .exhibition__third__main__must
          必須
        .exhibition__third__main__choice
          = f.select :category_id, options_for_select(@categories.map{|c|[c.name, c.id]},@parent.id), {}, {id: 'parent_category'}
          #children_wrapper.exhibitionPage__main__contents__detail__category__choose__added
            .exhibitionPage__main__contents__detail__category__choose1
              %select#child_category.exhibitionPage__main__contents__detail__category__choose--select{:name => "item[category_id]"}
                %option{"data-category" => "---", :value => "---"} ---
                - @parent.children.each do |child|
                  -if child == @children
                    %option{selected: "#{child.name}", "data-category" => "#{child.id}", :value => "#{child.id}"}
                      = child.name
                  - else
                    %option{"data-category" => "#{child.id}", :value => "#{child.id}"}
                      = child.name

          #grandchildren_wrapper.exhibitionPage__main__contents__detail__category__choose__added
            .exhibitionPage__main__contents__detail__category__choose2
              %select#grandchild_category.exhibitionPage__main__contents__detail__category__choose__box--select{:name => "item[category_id]"}
                %option{"data-category" => "---", :value => "---"} ---
                - @children.children.each do |grandchild|
                  -if grandchild == @category
                    %option{selected: "#{grandchild.name}", "data-category" => "#{grandchild.id}", :value => "#{grandchild.id}"}
                      = grandchild.name
                  - else
                    %option{"data-category" => "#{grandchild.id}", :value => "#{grandchild.id}"}
                      = grandchild.name


        -# .exhibition__third__main__size
        -#   サイズ
        -# .exhibition__third__main__must
        -#   必須
        -# .exhibition__third__main__size-form
        -#   .exhibition__third__main__size-form__main
        -#     サイズ選択
        -#   .exhibition__third__main__size-form__icon
        -#     = icon('fas', 'chevron-down')
        .exhibition__third__main__any
          = f.fields_for :brand do |brand|
            = brand.label "ブランド"
            %span.form-require-gray （任意）
            %div
              = brand.text_field :name, placeholder: "例）シャネル", value: "", class: "exhibition__third__main__any-form"
        .exhibition__third__main__type
          .exhibition__third__main__title
            商品の状態
          .exhibition__third__main__must
            必須
        .exhibition__third__main__type-choice
          .exhibition__third__main__type-choice__form
            = f.select :status,Item.statuses.keys.to_a
    .exhibition__forth
      .exhibition__forth__main
        .exhibition__forth__main__info
          配送について
        .exhibition__forth__main__burden
          = f.label '配送料の負担'
        .exhibition__forth__main__must
          必須
        .exhibition__forth__main__burden-form
          .exhibition__forth__main__burden-form__main
            = f.fields_for :shipping, @shipping do |shipping|
              = shipping.select :burden, Shipping.burdens.keys.to_a
        .exhibition__forth__main__choice
          選択してください
        .exhibition__forth__main__type
          配送の方法
        .exhibition__forth__main__must
          必須
        .exhibition__forth__main__burden-form
          .exhibition__forth__main__burden-form__main
            = f.fields_for :shipping do |shipping|
              = shipping.select :shipping_way, Shipping.shipping_ways.keys.to_a
        .exhibition__forth__main__choice
          選択してください
        .exhibition__forth__main__type
          発送元の地域
        .exhibition__forth__main__must
          必須
        .exhibition__forth__main__burden-form
          .exhibition__forth__main__burden-form__main
            = f.fields_for :shipping do |shipping|
              = shipping.select :area, Shipping.areas.keys.to_a
        .exhibition__forth__main__choice
          選択してください
        .exhibition__forth__main__type
          配送までの日数
        .exhibition__forth__main__must
          必須
        .exhibition__forth__main__burden-form
          .exhibition__forth__main__burden-form__main
            = f.fields_for :shipping do |shipping|
              = shipping.select :day, Shipping.days.keys.to_a
        .exhibition__forth__main__choice
          選択してください
    .exhibition__fifth
      .exhibition__fifth__main
        .exhibition__fifth__main__pricerange
          販売価格(¥300〜9,999,999)
        .exhibition__fifth__main__price
          .exhibition__fifth__main__price-box
            .exhibition__fifth__main__title
              販売価格
            .exhibition__fifth__main__must
              必須
          .exhibition__fifth__main__form
            = f.number_field :price, placeholder: '例）300'
        -#　あとでJS組む
        -# .exhibition__fifth__main__fee
        -#   販売手数料(10%)
        -#   .exhibition__fifth__main__fee1
        -#     = f.number_field :fee
        -# .exhibition__fifth__main__profit
        -#   販売利益
        -#   .exhibition__fifth__main__profit1
        -#     = f.number_field :profit
        .exhibition__fifth__main__btn
          = f.submit '変更する'
        .exhibition__fifth__main__text
          禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律に
          %br
          より処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

app/views/items/index.html.haml
%body
  .main
    %section.main-visual
      .contents-box
        .contents-box__title
          人生を変えるフリマアプリ
        .contents-box__subtitle
          FURIMAはだれでもかんたんに出品・購入できる
          %br
          フリマアプリです
        .contents-box__btn
          = link_to '#' ,class:'Appbtn' do
            = image_tag 'app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', width:  '170'
          = link_to '#' ,class: 'Googlebtn' do
            = image_tag 'google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg', width:  '170'
    %section.introduction
      .title
        FURIMAが選ばれる3つの理由
      %ul.reasons
        %li.reason
          .card
            .card__number
              1
            .card__picture
              = image_tag 'pict-reason-01.jpg', width: '250'
          .text
            %span
              3分
            ですぐに出品
          .description
            スマホで入力するだけで簡単に出品できる！
        %li.reason
          .card
            .card__number
              2
            .card__picture
              = image_tag 'pict-reason-02.jpg', width: '250'
          .text
            %span
              シンプル 
            で使いやすい
          .description
            めんどくさい入力は必要なく、検索も購入もスムーズ！
        %li.reason--last
          .card
            .card__number
              3
            .card__picture
              = image_tag 'pict-reason-03.jpg', width: '250'
          .text
            手数料
            %span
              業界最安
          .description
            最大3%でお得に出品&購入！
    %section.middle-ads
      .ads-box
        .ads-box__title
          会員数日本一位
        .ads-box__subtitle
          FURIMAは、フリマアプリで最も人気。
          %br
          出品・購入回数も業界最多です！
          %br
          ほしかったあの商品にも出会えるかもしれません。
        .ads-box__btn
          = link_to '#' ,class:'Appbtn' do
            = image_tag 'app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', width: '170'
          = link_to '#' ,class:'Googlebtn' do
            = image_tag 'google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg', width: '170'
    %section.characters
      .head
        FURIMAの特徴
      %ul.items
        %li.item
          .item__card
            = image_tag 'icon-01.png', width: '130'
          .item__title
            簡単に売り買いできる
          .item__text
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        %li.item
          .item__card
            = image_tag 'icon-03.png', width: '130'
          .item__title
            売上金は即日振込みに対応
          .item__text
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        %li.item
          .item__card
            = image_tag 'icon-04.png', width: '130'
          .item__title
            様々な支払いに対応
          .item__text
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
    %section.pickup-container
      .product-box
        .product-head
          = link_to '#' do
            .title
              商品一覧
        %ul.product-lists
          - @items.each do |item|
            %li.product-list 
              -if item.buyer_id == nil
                = link_to item_path(item.id)  do
                  .product-list__img
                    = image_tag item.images.first.image.url
                  .product-list__content
                    .name
                      = item.name
                    .price
                      = item.price
                      円

app/views/items/purchase_confirmation.html.haml
.confirmation-container__main
  .confirmation-container__main__contents
    %h2.confirmation-container__main__contents__head
      購入内容の確認
    %section.confirmation-container__main__contents__item
      .confirmation-container__main__contents__item__inner
        .confirmation-container__main__contents__item__inner__item-box
          %h3.confirmation-container__main__contents__item__inner__item-box__image
            = image_tag @item.images.first.image.url, width: '80', height: '80'
          .confirmation-container__main__contents__item__inner__item-box__detail
            %p.confirmation-container__main__contents__item__inner__item-box__detail__name
              = @item.name
            %p.confirmation-container__main__contents__item__inner__item-box__detail__price
              %span
                = "¥#{@item.price}"
              %spna.tax-and-shipping-fee
                = "（税込）#{@item.shipping.burden}"
    %section.confirmation-container__main__contents__item
      .confirmation-container__main__contents__item__inner
        %ul.confirmation-container__main__contents__item__inner__price-table
          %li.confirmation-container__main__contents__item__inner__price-table__left
            支払い金額
          %li.confirmation-container__main__contents__item__inner__price-table__right
            = "¥#{@item.price}"
        .confirmation-container__main__contents__item__inner__user-info
          .confirmation-container__main__contents__item__inner__user-info__top
            %h3
              支払い方法
            = link_to '変更する', card_path(current_user.id)
          %p.confirmation-container__main__contents__item__inner__user-info__text
            クレジットカード
            %br
            = "**** **** **** " + @customer_card.last4
            %br
            - exp_month = @customer_card.exp_month.to_s
            - exp_year = @customer_card.exp_year.to_s.slice(2,3)
            = '有効期限 '+ exp_month + " / " + exp_year
          %figure.card-logo
            = image_tag "#{@card_src}", width: '34', height: '20'
        .confirmation-container__main__contents__item__inner__user-info
          .confirmation-container__main__contents__item__inner__user-info__top
            %h3
              配送先
            = link_to '変更する', "#"
          %address.confirmation-container__main__contents__item__inner__user-info__text
            %p
              - post_first = @shipping_data.post_code.to_s.slice(0,3)
              - post_last = @shipping_data.post_code.to_s.slice(3,6)
              = '〒'+ post_first + "-" + post_last
              %br
              = @shipping_data.prefecture
              = @shipping_data.city
              = @shipping_data.address
              %br
              = @shipping_data.family_name
              = @shipping_data.first_name
        %section
          = link_to '購入する', purchase_card_path(@item.id), method: :post, class: 'buy-button'

app/views/items/search_by_ransack.html.haml
.search_by_ransack
  .container
    .container_contents
      #items.container_contents_main
        .container_contents_main__top
          検索結果
        .product-head
          = link_to '#' do
            .title
        %ul.product-lists
          - @items.each do |item|
            %li.product-list 
              = link_to item_path(item.id)  do
                .product-list__img
                  = image_tag item.images.first.image.url, width: '155', height: '155'
                .product-list__content
                  .name
                    = item.name
                  .price
                    = item.price
                    円

      .search-side
        = search_form_for @q, url: search_by_ransack_items_path,html: {class: 'search-detail'} do |f|
          %h3.search-detail__top
            詳細検索
          .search-detail__form-group
            = f.label :name_or_description_cont, "キーワード"
            = f.search_field :name_or_description_cont, placeholder: "例）値下げ", class: 'search-detail__form-group__input-default'
          .search-detail__form-group
            = f.label :brand_id_cont, "ブランド名から探す"
            = f.search_field :brand_id_cont, placeholder: "例）シャネル", class: 'search-detail__form-group__input-default'
          .search-detail__form-group
            = f.label :price, "価格" 
            .search-detail__form-group__price
              .min
                = f.number_field :price_gteq
              %span ~
              .max
                = f.number_field :price_lt
          .search-detail__form-group
            = f.label :status_eq_any, "商品の状態"
            .search-detail__form-group__checkbox
              .search-detail__form-group__checkbox__default
                = f.check_box :status_eq_any, { multiple: true }, 1, ''
                新品未使用
              .search-detail__form-group__checkbox__default
                = f.check_box :status_eq_any, { multiple: true }, 2, ''
                未使用に近い
              .search-detail__form-group__checkbox__default
                = f.check_box :status_eq_any, { multiple: true }, 3, ''
                目立った傷や汚れなし
              .search-detail__form-group__checkbox__default
                = f.check_box :status_eq_any, { multiple: true }, 4, ''
                やや傷や汚れあり
              .search-detail__form-group__checkbox__default
                = f.check_box :status_eq_any, { multiple: true }, 5, ''
                傷や汚れあり
              .search-detail__form-group__checkbox__default
                = f.check_box :status_eq_any, { multiple: true }, 6, ''
                全体的に状態が悪い
          .search-detail__form-group
            = f.label :shipping, "配送料の負担"
            .search-detail__form-group__checkbox
              .search-detail__form-group__checkbox__default
                = f.check_box :shipping_burden_eq_any, { multiple: true }, 1, ''
                送料込み（出品者負担）
              .search-detail__form-group__checkbox__default
                = f.check_box :shipping_burden_eq_any, { multiple: true }, 2, ''
                着払い（購入者負担）
          .search-detail__form-group
            = f.label :buyer_id, "販売状況"
            .search-detail__form-group__checkbox
              .search-detail__form-group__checkbox__default
                = f.check_box :buyer_id_null, as: :boolean, include_hidden: false
                販売中
              .search-detail__form-group__checkbox__default
                = f.check_box :buyer_id_not_null, as: :boolean, include_hidden: false
                売り切れ
          .submit-btn
            = f.submit

app/views/items/show.html.haml
- if @item.buyer_id.present? && @item.user_id == current_user.id
  - breadcrumb :my_item, @item
  = render partial: "layouts/breadcrumbs"
- elsif @item.buyer_id.present? && @item.buyer_id == current_user.id
  - breadcrumb :my_purchased_item, @item
  = render partial: "layouts/breadcrumbs"
.show-wrapper
  .show-main
    .show-main__contents
      .show-main__contents__item-box
        %h2.show-main__contents__item-box__name
          = @item.name
        .show-main__contents__item-box__images
          .show-main__contents__item-box__images__top
            = image_tag @item.images.first.image.url, width: '560', height: '346'
          %ul.show-main__contents__item-box__images__others
            - @item.images.each do |image|
              %li
                = image_tag image.image.url, width: '140', height: '87'
        .show-main__contents__item-box__price
          %span
            = "¥#{@item.price}"
          .show-main__contents__item-box__price__detail
            %span (税込)
            %span
              - if @item.shipping.burden_before_type_cast == 1
                送料込み
              - else
                着払い

        
        - if user_signed_in?
          - unless current_user.id == @item.user_id
            .show-main__contents__item-box__buy-btn
              - if @item.buyer_id.present?
                .show-main__contents__item-box__buy-btn__sold
                  売り切れました
              - else
                = link_to '購入画面に進む',purchase_confirmation_item_path(@item.id) , class: 'show-main__contents__item-box__buy-btn__available'
        - else
          .show-main__contents__item-box__buy-btn
            - if @item.buyer_id.present?
              .show-main__contents__item-box__buy-btn__sold
                売り切れました
            - else
              = link_to '購入画面に進む',purchase_confirmation_item_path(@item.id) , class: 'show-main__contents__item-box__buy-btn__available'
        .show-main__contents__item-box__description
          = simple_format @item.description
        .show-main__contents__item-box__table
          %table
            %tbody
              %tr
                %th 出品者
                %td
                  = @item.user.name
              %tr
                %th カテゴリ
                %td
                  = link_to @parent.name
                  %br
                  = link_to @children.name
                  %br
                  = link_to @category.name
              %tr
                %th ブランド
                %td
              %tr
                %th サイズ
                %td
              %tr
                %th 商品の状態
                %td
                  = @item.status
              %tr
                %th 配送料の負担
                %td
                  = @item.shipping.burden
              %tr
                %th 配送料の負担
                %td
                  = @item.shipping.shipping_way
              %tr
                %th 発送元の地域
                %td
                  = @item.shipping.area
              %tr
                %th 発送日の目安
                %td
                  = @item.shipping.day
        .show-main__contents__item-box__optional-area
          - if @item.users.include?(current_user)
            .show-main__contents__item-box__optional-area__like-btn-fill{data: {num: {favorites: @item.users.length}}}
              %i.fa.fa-star
              お気に入り
              = @item.users.length
          - else
            .show-main__contents__item-box__optional-area__like-btn-empty{data: {num: {favorites: @item.users.length}}}
              %i.fa.fa-star
              お気に入り
              = @item.users.length
          .show-main__contents__item-box__optional-area__report-btn{data: {item: {id: @item.id}}}
            = link_to  "#" do
              %i.fa.fa-flag
                不適切な商品の通報
      - if user_signed_in? && current_user.id == @item.user_id
        .show-main__contents__edit-destroy
          = link_to '商品の編集', edit_item_path(@item.id), class: 'show-main__contents__edit-destroy__edit-btn'
          %p or
          .show-main__contents__edit-destroy__destroy-btn この商品を削除する
      .show-main__contents__comment-box
        .show-main__contents__comment-box__new-comment
          = form_with(model: [@item, @comment], local: true) do |f|
            = f.text_area :text
            %p.show-main__contents__comment-box__new-comment__caution
              相手のことを考え丁寧なコメントを心がけましょう。
              %br
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            - if @item.buyer_id.present?
              .comment-when-sold
                売り切れのためコメントできません
            -else
              %button{type: 'submit'}
                %i.fa.fa-comment
                  コメントする
        .show-main__contents__comment-box__index
          .show-main__contents__comment-box__index__title
            ＜質問・コメント一覧＞
          %ul.show-main__contents__comment-box__index__comments
            - if @comments.present?
              - @comments.each do |comment|
                %li.show-main__contents__comment-box__index__comments__comment
                  .comment__username
                    = comment.user.name
                  .comment__content
                    = comment.text
            - else 
              .error-messege
                コメントがありません。
      %ul.show-main__contents__links
        %li
          = link_to '< 前の商品', item_path(@item.id - 1), class: "left"
        %li
          = link_to '後ろの商品 >', item_path(@item.id + 1), class: "right"
      .show-main__contents__related-items
        = link_to 'メンズをもっと見る', "#"

  .show-modal
    .show-modal__body
      .show-modal__body__messages
        .show-modal__body__messages__bold
          確認
        削除すると二度と復活できません
        %br
        %br
        本当に削除しますか？
      .show-modal__body__confirmation
        .show-modal__body__confirmation__cancel-btn
          キャンセル
        = link_to '削除する', item_path(@item.id), method: :delete, class: 'show-modal__body__confirmation__delete-btn'