config/routes.rb
Rails.application.routes.draw do
  get 'sessions/logout_page'
  get 'session/logout_page'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  get '/logout', to: 'sessions#logout_page'

  resources :users, only: [:new, :show] do
    collection do
      get :my_favorites
      get :my_items
      get :my_purchased_items
    end
  end
  
  resources :cards, only: [:new, :create, :show] do
    collection do
      delete :delete
    end
    member do
      post :purchase
      get :new_for_purchase
      post :create_for_purchase
    end
  end

  resources :profiles, only: [:new, :create] do
    collection do
      get 'step1'
      get 'step2'
    end
  end

  resources :shipping_datas, only: [:new, :create] do
    collection do
      get 'step1'
      get 'step2'
    end
  end


  resources :items, except: [:index] do
    collection do
      get :destroy_existing_image
    end
    
    member do
      get :purchase_confirmation
    end 

    collection do
      get :search_by_ransack
      get 'search'
      post :create_favorite
      post :destroy_favorite
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :comments,  only: :create
  end

  root 'items#index'


end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :card_id
    validates :customer_id
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  # before_action :set_card, except:[:create, :create_for_purchase]

  def new
    card = current_user.cards.first
    redirect_to card_path(current_user.id) if card.present?
  end

  def new_for_purchase
    card = current_user.cards.first
    @item_id = params[:id] 
    redirect_to card_path(current_user.id) if card.present?
  end

  def create
    Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
    customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
    )
    
    @card = Card.new(
      card_id: customer.default_card,
      customer_id: customer.id,
      user_id: current_user.id
    )
    if @card.save
      redirect_to action: :new
    else
      flash.now[:alert] = '登録に失敗しました。お手数ですが、もう一度やり直してください。'
      render :new
      return
    end
  end

  def create_for_purchase
    Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
    customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
    )
    
    @card = Card.new(
      card_id: customer.default_card,
      customer_id: customer.id,
      user_id: current_user.id
    )
    if @card.save
      redirect_to purchase_confirmation_item_path(params[:id])
    else
      flash.now[:alert] = '登録に失敗しました。お手数ですが、もう一度やり直してください。'
      render :new_for_purchase
      return
    end
  end

  def show
    card = current_user.cards.first
    if card.blank?
      redirect_to action: :new
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @customer_card = customer.cards.retrieve(card.card_id)

      card_brand = @customer_card.brand      
      case card_brand
      when "Visa"
        @card_src = "visa.png"
      when "JCB"
        @card_src = "jcb.png"
      when "MasterCard"
        @card_src = "master-card.png"
      when "American Express"
        @card_src = "american_express.png"
      when "Diners Club"
        @card_src = "dinersclub.png"
      when "Discover"
        @card_src = "discover.png"
      end
    end
  end

  def delete
    card = current_user.cards.first
    if card.present?
      Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end

    redirect_to action: :new
  end

  def purchase
    if current_user.id == Item.find(params[:id]).user_id
      redirect_to root_path 
    elsif Item.find(params[:id]).buyer_id.present?
      redirect_to root_path
    else
      card = current_user.cards.first
      if card.blank?
        redirect_to action: :new
        flash[:alert] = '購入にはクレジットカード登録が必要です'
      else
        @item = Item.find(params[:id])
        Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
        Payjp::Charge.create(
        amount: @item.price,
        customer: card.customer_id,
        currency: 'jpy'
        )
        if @item.update(buyer_id: current_user.id)
          redirect_to controller: :items, action: :show
          flash[:notice] = 'お買い上げいただき誠にありがとうございます。'
        else
          redirect_to controller: :items, action: :show
          flash[:alert] = '購入に失敗しました。お手数ですが、もう一度やり直してください。'
        end
      end
    end
  end

  private
  def set_card
    card = current_user.cards.first
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
- breadcrumb :new_card
= render partial: "layouts/breadcrumbs"
.container
  .container_contents
    .container_contents_main
      .container_contents_main_addcard
        支払い方法
        %hr
        .container_contents_main_addcard__inside
          = form_tag cards_path do
            %script.payjp-button{:src => "https://checkout.pay.jp", :type => "text/javascript" ,"data-text" => "クレジットカードを登録する", "data-submit-text" => "クレジットカードを登録する" ,"data-key" => "#{ Rails.application.credentials[:payjp][:public_key]}"}

    = render partial: "users/side-bar"

app/views/cards/new_for_purchase.html.haml
.container
  .container_contents
    .container_contents_main
      .container_contents_main_addcard
        支払い方法
        %hr
        .container_contents_main_addcard__inside
          = form_tag create_for_purchase_card_path(@item_id) do
            %script.payjp-button{:src => "https://checkout.pay.jp", :type => "text/javascript" ,"data-text" => "クレジットカードを登録する", "data-submit-text" => "クレジットカードを登録する" ,"data-key" => "#{ Rails.application.credentials[:payjp][:public_key]}"}
    = render partial: "users/side-bar"

app/views/cards/show.html.haml
- breadcrumb :my_card
= render partial: "layouts/breadcrumbs"
.container
  .container_contents
    .container_contents_main
      .container_contents_main__card-info
        .container_contents_main__card-info__top
          お支払い方法
        .container_contents_main__card-info__body
          %section.container_contents_main__card-info__body__inner
            .container_contents_main__card-info__body__inner__top
              クレジットカード情報
            .container_contents_main__card-info__body__inner__body
              %ul.container_contents_main__card-info__body__inner__body__logos
                %li.container_contents_main__card-info__body__inner__body__logos__logo
                  %figure
                    = image_tag "#{@card_src}", width: '49', height: '35'
                %li.container_contents_main__card-info__body__inner__body__logos__delete-btn
                  = link_to '削除する', delete_cards_path, method: :delete
              .container_contents_main__card-info__body__inner__body__number
                = "**** **** **** " + @customer_card.last4
              .container_contents_main__card-info__body__inner__body__expiration-date
                - exp_month = @customer_card.exp_month.to_s
                - exp_year = @customer_card.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year
          .container_contents_main__card-info__body__space

    = render partial: "users/side-bar"