config/routes.rb
Rails.application.routes.draw do
  get 'sessions/logout_page'
  get 'session/logout_page'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  get '/logout', to: 'sessions#logout_page'

  resources :users, only: [:new, :show] do
    collection do
      get :my_favorites
      get :my_items
      get :my_purchased_items
    end
  end
  
  resources :cards, only: [:new, :create, :show] do
    collection do
      delete :delete
    end
    member do
      post :purchase
      get :new_for_purchase
      post :create_for_purchase
    end
  end

  resources :profiles, only: [:new, :create] do
    collection do
      get 'step1'
      get 'step2'
    end
  end

  resources :shipping_datas, only: [:new, :create] do
    collection do
      get 'step1'
      get 'step2'
    end
  end


  resources :items, except: [:index] do
    collection do
      get :destroy_existing_image
    end
    
    member do
      get :purchase_confirmation
    end 

    collection do
      get :search_by_ransack
      get 'search'
      post :create_favorite
      post :destroy_favorite
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :comments,  only: :create
  end

  root 'items#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/buyer_shipping_data.rb
class BuyerShippingData < ApplicationRecord
  belongs_to :user
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :card_id
    validates :customer_id
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :text, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :item
  mount_uploader :image, ImageUploader

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :brand
  belongs_to :shipping
  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy 
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  accepts_nested_attributes_for :category
  accepts_nested_attributes_for :shipping
  accepts_nested_attributes_for :brand
  accepts_nested_attributes_for :images


  validates :name,length:{maximum:20}
  validates :description, length:{maximum:1000}
  validates :price,numericality:{greater_than_or_equal_to: 300} 

  with_options presence: true do
    validates :name
    validates :description
    validates :status
    validates :price
    validates :fee
    validates :profit
    validates :user_id
    validates :category_id 
    # validates :shipping_id
    validates :images

  end


  enum status: {
    新品未使用:1,未使用に近い:2,目立った傷や汚れなし:3,やや傷や汚れあり:4,傷や汚れあり:5,全体的に状態が悪い:6
  }
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  has_many :items
  
  with_options presence: true do
    validates :burden
    validates :area
    validates :day
  end
  enum burden: {
    送料込み（出品者負担）:1,着払い（購入者負担）:2
  }
  
  enum shipping_way:{
    '--':0,らくらくメール便:1,ゆうメール:2,
    レターパック:3,普通郵便:4,クロネコヤマト:5,
    ゆうパック:6,ゆうパケット:7
  }
  
  enum area:{
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  },_prefix: true
  
  enum day:{
    "1~2日で発送":1, "2~3日で発送":2, "4~7日で発送":3
  },_prefix: true

end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2], password_length: 7..128
  validates :name, presence: true, uniqueness: true

  def self.form_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
  has_one :profile, dependent: :destroy
  has_one :buyer_shipping_data, dependent: :destroy
  has_many :cards
  has_many :sns_credentials
  has_many :comments
  has_many :favorites
  has_many :items, dependent: :destroy
  has_many :favorite_items, through: :favorites, source: :item
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_breadcrumbs.html.haml
.breadcrumbs
  %ul.breadcrumbs__main
    %li.breadcrumbs__main__body
      = breadcrumbs separator: " ＞ ", class: "breadcrumbs-list"

app/views/layouts/_footer.html.haml
.banner
  .banner-contents
    .subtitle
      だれでもかんたん、人生を変えるフリマアプリ
    .title
      今すぐ無料ダウンロード！
    .banner-btn
      = link_to '#' ,class:'Appbtn' do
        = image_tag 'app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', width: '170'
      = link_to '#' ,class:'Googlebtn' do
        = image_tag src='google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg', width: '170'
.footer
  .footer__overviews
    .overview
      .head
        FURIMAについて
      %ul.contents
        %li.content
          = link_to '#' do
            会社概要（運営会社）
        %li.content
          = link_to '#' do
            プライバシーポリシー
        %li.content
          = link_to '#' do
            FURIMA利用規約
        %li.content
          = link_to '#' do
            ポイントに関する特約
    .overview
      .head
        FURIMAを見る
      %ul.contents
        %li.content
          = link_to '#' do
            カテゴリー一覧
        %li.content
          = link_to '#' do
            ブランド一覧
    .overview
      .head
        ヘルプ＆ガイド
      %ul.contents
        %li.content
          = link_to '#' do
            FURIMAガイド
        %li.content
          = link_to '#' do
            FURIMAロゴ利用ガイドライン
        %li.content
          = link_to '#' do
            お知らせ
  .footer__logo
    = link_to image_tag('logo-white.png', width: "140"),root_path
  .footer__company
    ©️FURIMA
= link_to new_item_path do
  .exhibition-btn
    .text
      出品する
    = image_tag "icon_camera.png",class:"icon"

app/views/layouts/_header.html.haml
%header.header
  .headerInner
    .mainHeader
      %h1.icon
        = link_to image_tag('logo.png', width: "140"), root_path
      .searchBox
        = search_form_for @q, url: search_by_ransack_items_path,html: {class: 'search-form'} do |f|
          = f.search_field :name_or_description_cont, placeholder: "キーワードから探す", class: 'search-form__input'
          %button.btn-search{ type: "submit"}
            .search-form__icon
              = image_tag 'icon-search 1.png',width: '20'
    .nav
      %ul.listsLeft
        %li.listsLeft__item--first
          = link_to 'カテゴリー', '#' 
          .tree.displayNone
            %ul.categoryTree
              %li.categoryTree--item{id: '1'}
              = link_to 'レディース','#'
        %li.listsLeft__item
          = link_to 'ブランド', '#', id: 'brandBtn'
      %ul.listsRight
        -if user_signed_in?
          %li.listsRight__item--login
            = link_to 'マイページ', user_path(current_user)
        -else
          %li.listsRight__item--login 
            = link_to 'ログイン', new_user_session_path
          %li.listsRight__item--new
            = link_to '新規会員登録', new_user_registration_path

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_sub_footer.html.haml
.confirmation-container__footer
  %nav.confirmation-container__footer__nav
    %ul
      %li
        = link_to 'プライバシーポリシー', "#"
      %li
        = link_to 'FURIMA利用規約', "#"
      %li
        = link_to '特定商取引に関する表記', "#"
  = link_to image_tag('logo.png',width: '120', height: '35', class: 'parchase-footer-logo'), root_path
  %p
    %small
      © FURIMA

app/views/layouts/_sub_header.html.haml
.confirmation-container
  .confirmation-container__header
    %h1
      = link_to image_tag('logo.png', width: '185', height: '49'), root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FleamarketSample75h
    = csrf_meta_tags
    = csp_meta_tag
    = include_gon
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
  %body
    = render 'layouts/header'
    = render 'layouts/notifications'
    = yield
    = render 'layouts/footer'

app/views/layouts/sub_application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FleamarketSample75h
    = csrf_meta_tags
    = csp_meta_tag
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    %div.sub-application-container
      = render 'layouts/sub_header'
      = yield
      = render 'layouts/sub_footer'